### ISSUE TITLE
[Bug]: Desktop client version 3.8.1 does not compile with gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

### ISSUE THREAD

**Issue by eehmke** [nextcloud/desktop#5652]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I downloaded the source code of desktop client version 3.8.1. 
Unpacked the package on my KDE Neon system in my home directory. 
Followed the steps described in the README.md file. 
On the 
cmake --build build --target install
step, I get these errors:

`/home/eggert/tmp/desktop-3.8.1/src/libsync/clientsideencryption.cpp:1736:10: error: call to deleted constructor of 'QCryptographicHash' [clang-diagnostic-error]
    auto hashAlgorithm = QCryptographicHash{QCryptographicHash::Sha256};
         ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcryptographichash.h:106:20: note: 'QCryptographicHash' has been explicitly marked deleted here
    Q_DISABLE_COPY(QCryptographicHash)
                   ^
/home/eggert/tmp/desktop-3.8.1/src/libsync/clientsideencryption.cpp:1762:14: error: call to deleted constructor of 'QCryptographicHash' [clang-diagnostic-error]
        auto hashAlgorithm = QCryptographicHash{QCryptographicHash::Sha256};
             ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qcryptographichash.h:106:20: note: 'QCryptographicHash' has been explicitly marked deleted here
    Q_DISABLE_COPY(QCryptographicHash)
                   ^
`

I could solve this issue by replacing the declaration in line1736 (and more occurrences) like this:

    auto* hashAlgorithm = new QCryptographicHash{QCryptographicHash::Sha256};

and change the references to that variable for pointer access. This works for me, but I am not sure this is the correct method.

### Steps to reproduce

Have a system with gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04). 
Compile the source code of desktop client version 3.8.1.

### Expected behavior

The source code should compile error free.

### Which files are affected by this bug

desktop-3.8.1/src/libsync/clientsideencryption.cpp

### Operating system

Linux

### Which version of the operating system you are running.

KDE Neon

### Package

Compiled it myself

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

3.8.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

The source code could be compiled error free until client version 3.8.0

**Comment by eehmke** [comment]
@camilasan That seems to be a lot of effort for a minor change. Can you get me started?

**Comment by eehmke** [comment]
Seems to be fixed in 3.8.2.
