### ISSUE TITLE
3.1.2 fails to build with shibboleth enabled

### ISSUE THREAD

**Issue by yopito** [nextcloud/desktop#2885]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

build of desktop 3.1.2 fine with shibboleth enabled  (**without** cmake argument `-DNO_SHIBBOLETH=True`).

FYI, I maintain the package of nextcloud desktop for the VoidLinux distribution, and version 3.1.1 build fine with the same building context (qt 5.15.2, gcc 10.2.1 , etc)

### Actual behaviour

build fails:
```
[ 43%] Building CXX object src/gui/CMakeFiles/nextcloud.dir/tray/NotificationHandler.cpp.o
[ 43%] Building CXX object src/gui/CMakeFiles/nextcloud.dir/creds/credentialsfactory.cpp.o
../../../src/gui/creds/credentialsfactory.cpp: In function 'OCC::AbstractCredentials* OCC::CredentialsFactory::create(const QString&)':
../../../src/gui/creds/credentialsfactory.cpp:43:24: error: invalid new-expression of abstract class type 'OCC::ShibbolethCredentials'
   43 |             return new ShibbolethCredentials;
      |                        ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../../src/gui/creds/credentialsfactory.cpp:22:
../../../src/gui/creds/shibbolethcredentials.h:43:7: note:   because the following virtual functions are pure within 'OCC::ShibbolethCredentials':
   43 | class ShibbolethCredentials : public AbstractCredentials
      |       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../../src/libsync/creds/httpcredentials.h:23,
                 from ../../../src/gui/creds/httpcredentialsgui.h:17,
                 from ../../../src/gui/creds/credentialsfactory.cpp:19:
../../../src/libsync/creds/abstractcredentials.h:46:21: note:     'virtual QString OCC::AbstractCredentials::password() const'
   46 |     virtual QString password() const = 0;
      |                     ^~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-gnu-zero-variadic-macro-arguments' may have been intended to silence earlier diagnostics
make[2]: *** [src/gui/CMakeFiles/nextcloud.dir/build.make:1290: src/gui/CMakeFiles/nextcloud.dir/creds/credentialsfactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1499: src/gui/CMakeFiles/nextcloud.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
=> ERROR: nextcloud-client-3.1.2_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/cmake.sh:78
```

### Steps to reproduce
1. grab source of desktop 3.1.2
2. launch packaging : install requirements in chroot and start build

### Client configuration
Client version:

Operating system: GNU/Linux (VoidLinux distribution)

OS language: US

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): distro VoidLinux

Installation path of client: n/a

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

Complete build log: https://gist.github.com/yopito/57d7c5682cc32ee3f6aa924f6c75e680#file-xbps-build-nextcloud-desktop-3-1-2-with-shibboleth-build-log

Edit: fix cmake parameter for build **with** shibboleth

**Comment by yopito** [comment]
build is fine without shibboleth support (`-DNO_SHIBBOLETH=True`)

**Comment by FlexW** [comment]
Why do you want to enable this option? This option deprecated.

**Comment by ivaradi** [comment]
I experienced the same in case of the Ubuntu and Debian packages. 

@FlexW I would happily not use this option, but without it compilation fails, as @yopito described.

**Comment by yopito** [comment]
@FlexW : thanks for your reply.  I wasn't aware that Shibboleth support was deprecated. Do you have pointer about it ?

And without this specific support, desktop client won't work in such a SAML env ? desktop user are supposed to use an app token instead ?

Thanks.

**Comment by FlexW** [comment]
Seems like a was a little bit to fast and https://github.com/nextcloud/client-building/pull/61 was not picked for 3.1.2.

@er-vin could you say something about this?

**Comment by er-vin** [comment]
This looks suspicious, on the v3.1.2 tag we didn't mess with the shibboleth code in any way. This was done only in master. I fail to see what could have been introduced between v3.1.1 and v3.1.2 which would cause this.

Could someone affected by this do a git bisect between v3.1.1 and v3.1.2 and let us know which is the faulty commit? Thanks in advance.

**Comment by er-vin** [comment]
Ah, actually I think I know. @FlexW in master you added a couple new pure virtual functions on AbstractCredentials. But master doesn't have ShibbolethCredentials anymore so it didn't get updated for that. Then this commit got cherry-picked in stable-3.1. We then didn't detect the issue because all of our builds are with NO_SHIBBOLETH=ON.

We never build with shibboleth because of the reason invoked: it's been unsupported for ages and will be completely gone in 3.2. Still we should probably make a fix for that situation in stable-3.1 should be very small. Fix will be shipped with 3.1.3.
