### ISSUE TITLE
[Bug]: systray.mm:21:63: error: use of u ndeclared identifier 'UNNotificationPresentationOptionBanner' with macOS < 11.0

### ISSUE THREAD

**Issue by ra1nb0w** [nextcloud/desktop#4557]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Compiling nextcloud client 3.5.1 on macOS 10.14 I get the following error:

```
:info:build /opt/local/var/macports/build/_Users_rainbow_sources_github_macports-ports_www_nextcloud-client/nextcloud-client/work/desktop-3.5.1/src/gui/systray.mm:21:63: error: use of u
ndeclared identifier 'UNNotificationPresentationOptionBanner'; did you mean 'UNNotificationPresentationOptionBadge'?
:info:build     completionHandler(UNNotificationPresentationOptionSound + UNNotificationPresentationOptionBanner);
:info:build                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Version 3.4.4 was working perfectly.

This happen because `UNNotificationPresentationOptionBanner` is available from macOS 11.0+ and therefore using that API doesn't respect the system requirement (macOS 10.12+)

### Steps to reproduce

Build the software as described in the guide.
This is part of macports [port](https://ports.macports.org/port/nextcloud-client/details/) update.

### Expected behavior

The software should compile without any issue.

### Which files are affected by this bug

systray.mm

### Operating system

Mac OS

### Which version of the operating system you are running.

10.14

### Package

Compiled it myself

### Nextcloud Server version

24.0.0

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @ra1nb0w ,

We now have a fix for builds on macOS 10.14 and up which should hopefully be merged soon. Unfortunately, with us now using the UserNotification framework for notifications we will not be able to support macOS versions pre-10.14 and will update our system requirements to reflect this.

Thank you for reporting this issue!

**Comment by ra1nb0w** [comment]
Thank you Claudio. I note this requirement change in macports and I will wait the merge.

**Comment by claucambra** [comment]
Hi @mascguy I have opened #4720 with your suggested changes to fix this issue, thanks for sharing

**Comment by mascguy** [comment]
> Hi @mascguy I have opened #4720 with your suggested changes to fix this issue, thanks for sharing

No problem, thank you for the quick response!
